In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
df = pd.read_csv('pakistan_intellectual_capital.csv')

In [2]:
df

,Unnamed: 0,S#,Teacher Name,University Currently Teaching,Department,Province University Located,Designation,Terminal Degree,Graduated from,Country,Year,Area of Specialization/Research Interests,Other Information
0,2,3,Dr. Abdul Basit,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,Software Engineering & DBMS,NaN
1,4,5,Dr. Waheed Noor,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,DBMS,NaN
2,5,6,Dr. Junaid Baber,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,"Information processing, Multimedia mining",NaN
3,6,7,Dr. Maheen Bakhtyar,University of Balochistan,Computer Science & IT,Balochistan,Assistant Professor,PhD,Asian Institute of Technology,Thailand,NaN,"NLP, Information Retrieval, Question Answering...",NaN
4,24,25,Samina Azim,Sardar Bahadur Khan Women's University,Computer Science,Balochistan,Lecturer,BS,Balochistan University of Information Technolo...,Pakistan,2005.0,VLSI Electronics DLD Database,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1137,1974,1975,Dr. Ahmar Rashid,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Associate Professor,PhD,JNU,South Korea,NaN,"Electrical Impedance Tomography, Inverse algor...",NaN
1138,1975,1976,Dr. Fawad Hussain,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Associate Professor,PhD,Grenoble,France,NaN,"Machine Learning, Big Data Anaysis, Data Minin...",NaN
1139,1977,1978,Dr. Rashad M Jillani,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Assistant Professor,PhD,Florida Atlantic University,USA,2012.0,"Digital Multimedia Systems, Video Compression ...",NaN
1140,1979,1980,Dr. Shahabuddin Ansari,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Assistant Professor,PhD,Ghulam Ishaq Khan Institute of Science and Tec...,Pakistan,NaN,"Medical Image Processing and Analysis, Digital...",NaN
1141,1980,1981,Dr. Sajid Anwar,Ghulam Ishaq Khan Institute,Computer Science and Engineering,KPK,Assistant Professor,PhD,Seoul National University,South Korea,NaN,"Pruning and Quantizing CNN, GPGPU,",NaN

In [3]:
df.isnull()

,Unnamed: 0,S#,Teacher Name,University Currently Teaching,Department,Province University Located,Designation,Terminal Degree,Graduated from,Country,Year,Area of Specialization/Research Interests,Other Information
0,False,False,False,False,False,False,False,False,False,False,True,False,True
1,False,False,False,False,False,False,False,False,False,False,True,False,True
2,False,False,False,False,False,False,False,False,False,False,True,False,True
3,False,False,False,False,False,False,False,False,False,False,True,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1137,False,False,False,False,False,False,False,False,False,False,True,False,True
1138,False,False,False,False,False,False,False,False,False,False,True,False,True
1139,False,False,False,False,False,False,False,False,False,False,False,False,True
1140,False,False,False,False,False,False,False,False,False,False,True,False,True
1141,False,False,False,False,False,False,False,False,False,False,True,False,True

In [4]:
df.isnull().sum()

Unnamed: 0                                      0
S#                                              0
Teacher Name                                    0
University Currently Teaching                   0
Department                                      0
Province University Located                     0
Designation                                    19
Terminal Degree                                 4
Graduated from                                  0
Country                                         0
Year                                          653
Area of Specialization/Research Interests     519
Other Information                            1018
dtype: int64

In [2]:
!pip install fuzzywuzzy

Requirement already satisfied: fuzzywuzzy in c:\python312\lib\site-packages (0.18.0)

In [3]:
import fuzzywuzzy # pip install fuzzywuzzy
from fuzzywuzzy import process

ModuleNotFoundError: No module named 'fuzzywuzzy'

In [ ]:
df.head()

In [ ]:
countries = df['Country'].unique()
countries.sort()
countries

In [8]:
df['Country'] = df['Country'].str.lower()
df['Country'] = df['Country'].str.strip()

In [ ]:
countries = df['Country'].unique()
countries.sort()
countries

In [12]:
!pip show fuzzywuzzy

Name: fuzzywuzzy
Version: 0.18.0
Summary: Fuzzy string matching in python
Home-page: https://github.com/seatgeek/fuzzywuzzy
Author: Adam Cohen
Author-email: adam@seatgeek.com
License: GPLv2
Location: C:\Python312\Lib\site-packages
Requires:
Required-by: